---
name: "release"

on:
  push:
    branches:
      - "main"

# https://github.com/marketplace/actions/setup-miniconda
jobs:
  deploy:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      # - name: Clone repo
      #   shell: bash -el {0}
      #   run: git clone https://github.com/Hauptman-Woodward/Marco_Polo.git

      # - name: Conda info
      #   shell: bash -el {0}
      #   run: conda info

      # - name: Conda list
      #   shell: pwsh
      #   run: conda list

      # - name: Run Pyinstaller
      #   shell: bash -el {0}
      #   run: pyinstaller Marco_Polo/distrib/Polo.spec
      
      # - name: Make release
      #   run: |
      #     echo "done!"

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: false
      #     title: "Development Build"
      #     files: |
      #       LICENSE.txt
      #       Marco_Polo/

