name: poloUpdate
channels:
  - defaults
dependencies:
  - tensorflow=1.14.0
  - pyqt
  - ca-certificates
  - certifi
  - openssl
  - jinja2
  - requests
  - matplotlib
  - pyinstaller
  - pip:
    - molmass
    - python-pptx
