name: poloUpdate
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - absl-py=1.3.0
  - alsa-lib=1.2.8
  - altgraph=0.17.3
  - astor=0.8.1
  - attr=2.5.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=38.0.4
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.5.0
  - fftw=3.3.10
  - flit-core=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - gast=0.5.3
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpc-cpp=1.48.1
  - grpcio=1.48.1
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.33
  - h5py=3.7.0
  - harfbuzz=6.0.0
  - hdf5=1.10.6
  - icu=70.1
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - jack=1.9.22
  - jinja2=3.1.2
  - jpeg=9e
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20220623.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - libllvm10=10.0.1
  - libllvm15=15.0.7
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.2
  - libprotobuf=3.20.3
  - libsndfile=1.2.0
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.1
  - lz4-c=1.9.4
  - macholib=1.16.2
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpg123=1.31.2
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.4
  - nspr=4.35
  - nss=3.88
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=3.0.8
  - packaging=22.0
  - pcre=8.45
  - pcre2=10.40
  - pillow=9.4.0
  - pip=22.3.1
  - pixman=0.40.0
  - ply=3.11
  - protobuf=3.20.3
  - pthread-stubs=0.4
  - pulseaudio=16.1
  - pycparser=2.21
  - pyinstaller=5.1
  - pyinstaller-hooks-contrib=2023.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python-pptx=0.6.21
  - python_abi=3.7
  - qt-main=5.15.8
  - qt-webengine=5.15.8
  - qtwebkit=5.212
  - re2=2022.06.01
  - readline=8.2
  - requests=2.28.1
  - scipy=1.7.3
  - setuptools=65.6.3
  - sip=6.7.2
  - six=1.16.0
  - sqlite=3.40.1
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - termcolor=2.1.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - unicodedata2=14.0.0
  - urllib3=1.26.14
  - werkzeug=2.2.2
  - wheel=0.38.4
  - wrapt=1.14.1
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xlsxwriter=3.0.8
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - molmass
