name: poloUpdate
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - tensorflow=1.13
  - pip=22.3.1
  - python=3.7
  - pyqt=5.15
  - ca-certificates
  - certifi
  - openssl
  - jinja2
  - requests
  - matplotlib
  - pyinstaller
  - brotlipy
  - libxcb
