name: poloUpdate
channels:
  - defaults
dependencies:
  - tensorflow=1.14.0
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - pip=22.3.1
  - python=3.7
  - pyqt
  - ca-certificates
  - certifi
  - openssl
  - jinja2
  - requests
  - matplotlib
  - pyinstaller
  - brotlipy
