name: poloUpdate
channels:
  - defaults
dependencies:
  - tensorflow=1.14.0
  - pip=22.3.1
  - python=3.7
  - pyqt
  - ca-certificates
  - certifi
  - openssl
  - jinja2
  - requests
  - matplotlib
  - pyinstaller
  - pip:
    - molmass
    - python-pptx
